*** Variables *** 
${URL_Stag}  https://stag.utb.cz/
${URL_UTB}  https://www.utb.cz/
${URL_Prohlizeni}  https://stag.utb.cz/portal/studium/prohlizeni.html
${URL_Uchazec}  https://stag.utb.cz/portal/studium/uchazec
${URL_Absolvent}  https://stag.utb.cz/portal/studium/absolvent
${URL_WebSluzby}  https://stag-ws.utb.cz/ws/web/
${URL_ECTS}  https://portal2.utb.cz/portal/studium/uchazec/ects-prijezdy.html
${URL_Login_Udaje}  https://user.utb.cz/
${URL_Kvalita_Vyuky}  https://stag.utb.cz/portal/studium/kvalita-vyuky
${URL_Moje_Studium}  https://stag.utb.cz/portal/studium/moje-studium
${URL_Zmena_Hesla}  https://portal.utb.cz/

${URL_Prubeh_Studia}  https://stag.utb.cz/portal/studium/moje-studium/index.html
${URL_Vizualizace_Studia}  https://stag.utb.cz/portal/studium/moje-studium/vizualizace.html
${URL_Zbyvajici_Povinnosti}  https://stag.utb.cz/portal/studium/moje-studium/zbyvajici-povinnosti.html
${URL_Zapis_Terminy}  https://stag.utb.cz/portal/studium/moje-studium/zkousky.html
${URL_Moje_Udaje}  https://stag.utb.cz/portal/studium/moje-studium/moje-udaje.html
${URL_Semestralni_Prace}  https://stag.utb.cz/portal/studium/moje-studium/odevzdavani-praci.html
${URL_Soubory_Studenta}  https://stag.utb.cz/portal/studium/moje-studium/soubory-studenta.html
${URL_Predzapis}  https://stag.utb.cz/portal/studium/moje-studium/predzapis.html
${URL_Graficky_Predzapis}  https://stag.utb.cz/portal/studium/moje-studium/graficky-predzapis.html
${URL_Krouzkovy_Predzapis}  https://stag.utb.cz/portal/studium/moje-studium/krouzkovy-predzapis.html
${URL_Burza_Zapisu}  https://stag.utb.cz/portal/studium/moje-studium/burza-zapisu.html
${URL_Temata_VSKP}  https://stag.utb.cz/portal/studium/moje-studium/podklady-vskp.html
${URL_Kvalifikacni_Prace}  https://stag.utb.cz/portal/studium/moje-studium/kvalifikacni-prace.html
${URL_Kontrola_Plagiatorstvi}  https://stag.utb.cz/portal/studium/moje-studium/plagiaty.html
${URL_Praxe}  https://stag.utb.cz/portal/studium/moje-studium/praxestudent.html
${URL_ECTS_Vyjezdy}  https://stag.utb.cz/portal/studium/moje-studium/ects-vyjezdy.html
${URL_ECTS_Prijezdy}  https://stag.utb.cz/portal/studium/moje-studium/ects-prijezdy.html
${URL_Hodnoceni_Kvality}  https://stag.utb.cz/portal/studium/moje-studium/hodnoceni-kvality.html
${URL_Automaticke_Zpravy}  https://stag.utb.cz/portal/studium/moje-studium/automaticke-zpravy.html
${URL_Upominky}  https://stag.utb.cz/portal/studium/moje-studium/reminder.html
${URL_Nahlizeni_Spisu}  https://stag.utb.cz/portal/studium/moje-studium/nahlizeni-do-spisu.html
${URL_Registr_Dluzniku}  https://stag.utb.cz/portal/studium/moje-studium/registr-dluzniku.html